"""Agregar modulo Servicio WOW 2026 (encuestas y evaluadores)

Revision ID: a02167765d41
Revises: a87b19768895
Create Date: 2026-09-23 09:21:30.023580

Puramente aditiva: crea las 13 tablas del módulo Servicio WOW 2026
(survey_wow_*, evaluator_areas, employees, sampling_configs,
schedule_entries, evaluation_assignments). No toca ninguna tabla existente.

El autogenerate original también propuso cambios sobre `audit_attachments`
(tipo de `is_external` y FKs sin ondelete); se quitaron a mano porque son
una desviación preexistente de la SQLite local, ajena a este módulo.

⚠️ main.py corre init_db() → create_all() al arrancar: si la app se levanta
con estos modelos ANTES de aplicar esta revisión, las tablas ya existirán y
`upgrade` fallará. En ese caso usar `alembic stamp a02167765d41`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02167765d41'
down_revision: Union[str, None] = 'a87b19768895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluator_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('survey_wow_criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('survey_wow_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('survey_wow_departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False, comment="Nombre del departamento evaluado (ej: 'Gestión Humana', 'RMA', 'Almacén')"),
    sa.Column('group_name', sa.String(length=120), nullable=True, comment="Nivel de consolidación de 'Resultados Generales' (ej: 'Gestión Administrativa / Soporte')"),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('name_key', sa.String(length=150), nullable=False, comment='Nombre normalizado (sin tildes, mayúsculas, espacios simples) — clave de upsert'),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('dept_path', sa.String(length=255), nullable=True, comment="'RutaDepto' del listado"),
    sa.Column('sub_department', sa.String(length=150), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_eligible_override', sa.Boolean(), nullable=True, comment='null = reglas automáticas; True/False = forzar elegibilidad'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['evaluator_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_key')
    )
    op.create_index(op.f('ix_employees_area_id'), 'employees', ['area_id'], unique=False)
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_table('sampling_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('titular_cap', sa.Integer(), nullable=False),
    sa.Column('suplentes_por_departamento', sa.Integer(), nullable=False),
    sa.Column('antiguedad_minima_dias', sa.Integer(), nullable=False),
    sa.Column('carga_alerta', sa.Integer(), nullable=False),
    sa.Column('areas_excluidas', sa.JSON(), nullable=True),
    sa.Column('personas_excluidas', sa.JSON(), nullable=True),
    sa.Column('evitar_repeticion', sa.JSON(), nullable=True),
    sa.Column('puestos_sin_interaccion_regex', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['survey_wow_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_table('schedule_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=120), nullable=False, comment="'Departamento evaluado' de la hoja Evaluadores (ej: 'CAJA – Gurabo')"),
    sa.Column('schedule_number', sa.Integer(), nullable=True, comment="'No.' del Cronograma (varias listas pueden compartirlo, ej: Caja)"),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=60), nullable=True),
    sa.Column('send_date', sa.Date(), nullable=True),
    sa.Column('tabulation_date', sa.Date(), nullable=True),
    sa.Column('disclosure_date', sa.Date(), nullable=True),
    sa.Column('report_delivery_date', sa.Date(), nullable=True),
    sa.Column('evaluator_areas_raw', sa.Text(), nullable=True, comment="'Áreas que evalúan' tal cual"),
    sa.Column('internal_sample_raw', sa.String(length=80), nullable=True, comment="'Muestra interna' tal cual"),
    sa.Column('external_sample_raw', sa.String(length=80), nullable=True, comment="'Muestra Externa' tal cual"),
    sa.Column('internal_sample_size', sa.Integer(), nullable=True),
    sa.Column('external_sample_size', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False, comment='ENCUESTAS_CERRADAS del script: la lista ya no se vuelve a sortear'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['survey_wow_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['survey_wow_departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'list_name', name='uq_schedule_entry_list')
    )
    op.create_index(op.f('ix_schedule_entries_cycle_id'), 'schedule_entries', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_department_id'), 'schedule_entries', ['department_id'], unique=False)
    op.create_table('survey_wow_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('survey_type', sa.String(length=20), nullable=False, comment="'interno' | 'externo' (SurveyType)"),
    sa.Column('branch', sa.String(length=60), nullable=True, comment='Sucursal, si aplica'),
    sa.Column('subprocess', sa.String(length=60), nullable=True, comment='Despacho / Ruta (Almacén externo)'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('list_name', sa.String(length=120), nullable=True, comment="Solo internos: nombre de la lista de evaluadores ('CAJA – Gurabo'). Enlaza el formulario con su ScheduleEntry."),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['survey_wow_cycles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['survey_wow_departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'department_id', 'survey_type', 'branch', 'subprocess', name='uq_survey_wow_form_identity')
    )
    op.create_index(op.f('ix_survey_wow_forms_cycle_id'), 'survey_wow_forms', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_survey_wow_forms_department_id'), 'survey_wow_forms', ['department_id'], unique=False)
    op.create_index(op.f('ix_survey_wow_forms_survey_type'), 'survey_wow_forms', ['survey_type'], unique=False)
    op.create_table('evaluation_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_entry_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_area_id', sa.Integer(), nullable=True, comment="'Área evaluadora (cronograma)' — estrato del muestreo"),
    sa.Column('role', sa.String(length=20), nullable=False, comment="'titular' | 'suplente' (AssignmentRole)"),
    sa.Column('status', sa.String(length=20), nullable=False, comment="'pendiente' | 'completo' (AssignmentStatus)"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluator_area_id'], ['evaluator_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_entry_id'], ['schedule_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_entry_id', 'employee_id', name='uq_assignment_unique')
    )
    op.create_index(op.f('ix_evaluation_assignments_employee_id'), 'evaluation_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_evaluation_assignments_schedule_entry_id'), 'evaluation_assignments', ['schedule_entry_id'], unique=False)
    op.create_index(op.f('ix_evaluation_assignments_status'), 'evaluation_assignments', ['status'], unique=False)
    op.create_table('survey_wow_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False, comment='1 = primera columna de pregunta del export'),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False, comment="'likert_5' | 'text' | 'identifier' (QuestionType)"),
    sa.Column('criteria_id', sa.Integer(), nullable=True, comment='Solo internos: criterio de la rúbrica al que corresponde'),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['criteria_id'], ['survey_wow_criteria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['survey_wow_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'order', name='uq_survey_wow_question_order')
    )
    op.create_index(op.f('ix_survey_wow_questions_form_id'), 'survey_wow_questions', ['form_id'], unique=False)
    op.create_table('survey_wow_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('external_response_id', sa.Integer(), nullable=False, comment="Columna 'ID' del export de Forms (deduplicación por formulario)"),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['survey_wow_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'external_response_id', name='uq_survey_wow_response_dedupe')
    )
    op.create_index(op.f('ix_survey_wow_responses_form_id'), 'survey_wow_responses', ['form_id'], unique=False)
    op.create_table('survey_wow_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value_score', sa.Integer(), nullable=True, comment='1-5 (likert_5)'),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_wow_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['survey_wow_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_survey_wow_answer_unique')
    )
    op.create_index(op.f('ix_survey_wow_answers_question_id'), 'survey_wow_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_survey_wow_answers_response_id'), 'survey_wow_answers', ['response_id'], unique=False)
    op.create_table('survey_wow_nominations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('nominee_name', sa.String(length=150), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['survey_wow_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id')
    )
    op.create_index(op.f('ix_survey_wow_nominations_nominee_name'), 'survey_wow_nominations', ['nominee_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_wow_nominations')
    op.drop_index(op.f('ix_survey_wow_answers_response_id'), table_name='survey_wow_answers')
    op.drop_index(op.f('ix_survey_wow_answers_question_id'), table_name='survey_wow_answers')
    op.drop_table('survey_wow_answers')
    op.drop_index(op.f('ix_survey_wow_responses_form_id'), table_name='survey_wow_responses')
    op.drop_table('survey_wow_responses')
    op.drop_index(op.f('ix_survey_wow_questions_form_id'), table_name='survey_wow_questions')
    op.drop_table('survey_wow_questions')
    op.drop_index(op.f('ix_evaluation_assignments_status'), table_name='evaluation_assignments')
    op.drop_index(op.f('ix_evaluation_assignments_schedule_entry_id'), table_name='evaluation_assignments')
    op.drop_index(op.f('ix_evaluation_assignments_employee_id'), table_name='evaluation_assignments')
    op.drop_table('evaluation_assignments')
    op.drop_index(op.f('ix_survey_wow_forms_survey_type'), table_name='survey_wow_forms')
    op.drop_index(op.f('ix_survey_wow_forms_department_id'), table_name='survey_wow_forms')
    op.drop_index(op.f('ix_survey_wow_forms_cycle_id'), table_name='survey_wow_forms')
    op.drop_table('survey_wow_forms')
    op.drop_index(op.f('ix_schedule_entries_department_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_cycle_id'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_table('sampling_configs')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_area_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('survey_wow_departments')
    op.drop_table('survey_wow_cycles')
    op.drop_table('survey_wow_criteria')
    op.drop_table('evaluator_areas')
    # ### end Alembic commands ###
